### ISSUE TITLE
Yagdra - Auto-attacks minerals, vespene and look-out towers; also can't add onto creep

### ISSUE THREAD

**Issue by OUsnakebyte** [jrtoman/SC2-Complete-Edition#3]
Love the Yagdra add, but it also auto-attacks attacks every clickable item on the field (minerals, vespene, etc.).  Also you can't spawn it onto the creep.

**Comment by jrtoman** [comment]
Yagdra was working in the earlier version of the mod, up until i started experimenting with burrowing with him and at some point introduced a regression.
