### ISSUE TITLE
Zerg AI multiple Leviathans - computer zerg spawns multiple Leviathans

### ISSUE THREAD

**Issue by OUsnakebyte** [jrtoman/SC2-Complete-Edition#4]
When playing against (or with) a single computer/AI Zerg, it is allowed to spawn multiple Leviathans.  But the human can only spawn one.

**Comment by jrtoman** [comment]
This is a know issue, one which I have been unable to root cause, but have also experienced this first hand. All the validator's as far as I'm concerned are correct, and are setup to limit the unit to 1 leviathan if one already exists for the given player/AI.

**Comment by OUsnakebyte** [comment]
Cool - it makes playing against Zerg one helluva challenge, that's for sure!  ;)
