### ISSUE TITLE
Stone Zealot

### ISSUE THREAD

**Issue by jotapex** [jrtoman/SC2-Complete-Edition#8]
I've found issue in protoss robotics facility :
in the "stone zealot" icon  also spawn an disruptor , "disruptor" icon is missing . you can replace it for removing one of the "observer" icons ( you have it twice) . also the original colossus is missing . thanks ... hope you can fix it

**Comment by jrtoman** [comment]
Do you have any know how on how to use the mod editor? I'm currently lacking the time to work on the mod and may need to do some handoff to get bugs fixed on a timely basis.

**Comment by jotapex** [comment]
sorry ... I don't have too much knowledge about how to use mod editor
